name: "Build docker image"
description: "Build docker image"

inputs:
  DOCKER_REGISTRY:
    description: "Docker registry"
    required: true

  DOCKER_REGISTRY_USERNAME:
    description: "Docker registry username"
    required: true

  DOCKER_REGISTRY_PASSWORD:
    description: "Docker registry password"
    required: true

  DOCKER_REPOSITORY:
    description: "Docker repository"
    required: true

  DOCKER_TARGET_PLATFORMS:
    description: "Docker buildx target platforms"
    required: false
    default: "linux/amd64" # change to "linux/amd64,linux/arm64" to support also arm64

  DOCKERFILE_PATH:
    description: "Path to Dockerfile"
    required: false
    default: "Dockerfile"

  DOCKER_BUILD_ARGS:
    description: "Docker build arguments"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ inputs.DOCKER_REGISTRY_USERNAME }}
        password: ${{ inputs.DOCKER_REGISTRY_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up tags
      id: build-tags
      shell: bash
      env:
        REGISTRY: ${{ inputs.DOCKER_REGISTRY }}
        REPOSITORY: ${{ inputs.DOCKER_REPOSITORY }}
      run: |
        IMAGE_NAME=$REGISTRY/$REPOSITORY
        echo "COMMIT_REF=${IMAGE_NAME}:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "BUILD_NUMBER=${IMAGE_NAME}:${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "LATEST=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
        else
          echo "BUILD_NUMBER=${IMAGE_NAME}:dev-${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "LATEST=${IMAGE_NAME}:dev-latest" >> $GITHUB_OUTPUT
        fi

    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        platforms: ${{ inputs.DOCKER_TARGET_PLATFORMS }}
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ${{ inputs.DOCKERFILE_PATH }}
        tags: |
          ${{ steps.build-tags.outputs.BUILD_NUMBER }}
          ${{ steps.build-tags.outputs.COMMIT_REF }}
          ${{ steps.build-tags.outputs.LATEST }}
        build-args: |
          ${{ inputs.DOCKER_BUILD_ARGS }}
