name: "Build Docker Image"

on:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_PASSWORD:
        description: "Docker registry password"
        required: true
      DOCKER_BUILD_ARGS:
        description: "Docker build arguments"
        required: false

    inputs:
      DOCKER_REGISTRY:
        description: "Docker registry"
        required: true
        type: string
      DOCKER_REGISTRY_USERNAME:
        description: "Docker registry username"
        required: true
        type: string
      DOCKER_REPOSITORY:
        description: "Docker repository"
        required: true
        type: string
      DOCKER_TARGET_PLATFORMS:
        description: "Docker buildx target platforms"
        required: false
        default: "linux/amd64"
        type: string
      DOCKERFILE_PATH:
        description: "Path to Dockerfile"
        required: false
        default: "Dockerfile"
        type: string
      DOCKER_CONTEXT:
        description: "Path to Docker context"
        required: false
        default: "."
        type: string
      DOCKER_BUILD_ARGS:
        description: "Docker build arguments"
        required: false
        type: string
      PUBLISH:
        description: "Publish images"
        required: false
        default: true
        type: boolean
      BUILD_CACHE:
        description: "Option to use cache for build, by default it is enabled"
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.DOCKER_REGISTRY }}
          username: ${{ inputs.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags
        id: build-tags
        shell: bash
        env:
          REGISTRY: ${{ inputs.DOCKER_REGISTRY }}
          REPOSITORY: ${{ inputs.DOCKER_REPOSITORY }}
        run: |
          IMAGE_NAME=$REGISTRY/$REPOSITORY
          echo "COMMIT_REF=${IMAGE_NAME}:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BUILD_NUMBER=${IMAGE_NAME}:${{ github.run_number }}" >> $GITHUB_OUTPUT
            echo "LATEST=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          else
            echo "BUILD_NUMBER=${IMAGE_NAME}:dev-${{ github.run_number }}" >> $GITHUB_OUTPUT
            echo "LATEST=${IMAGE_NAME}:dev-latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          platforms: ${{ inputs.DOCKER_TARGET_PLATFORMS }}
          push: ${{ inputs.PUBLISH }}
          cache-from: ${{ inputs.BUILD_CACHE && 'type=gha' || '' }}
          cache-to: ${{ inputs.BUILD_CACHE && 'type=gha,mode=max' || '' }}
          file: ${{ inputs.DOCKERFILE_PATH }}
          tags: |
            ${{ steps.build-tags.outputs.BUILD_NUMBER }}
            ${{ steps.build-tags.outputs.COMMIT_REF }}
            ${{ steps.build-tags.outputs.LATEST }}
          build-args: |
            ${{ inputs.DOCKER_BUILD_ARGS }}
            ${{ secrets.DOCKER_BUILD_ARGS || '' }}
